<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gsp</string>
		<string>tag</string>
	</array>
	<key>injections</key>
	<dict>
		<key>text.html.gsp - (meta.embedded.block.gsp | meta.embedded.line.gsp | meta.tag | comment), meta.tag string.quoted</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#el_expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s*)(?=&lt;%(?=\s))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.leading.erb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)(\s*$\n)?</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.trailing.erb</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#scriptlet</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#scriptlet</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JavaServer Pages</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#xml_tags</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>&lt;%--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gsp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--%&gt;</string>
			<key>name</key>
			<string>comment.block.gsp</string>
		</dict>
		<key>declaration</key>
		<dict>
			<key>begin</key>
			<string>&lt;%!</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.gsp</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.java</string>
			<key>end</key>
			<string>(%)&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.gsp</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>source.java</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.line.declaration.gsp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<key>el_expression</key>
		<dict>
			<key>begin</key>
			<string>\$\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.gsp</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.java</string>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.gsp</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>source.java</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.line.el_expression.gsp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>begin</key>
			<string>&lt;%=</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.gsp</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.java</string>
			<key>end</key>
			<string>(%)&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.gsp</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>source.java</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.line.expression.gsp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<key>scriptlet</key>
		<dict>
			<key>begin</key>
			<string>&lt;%</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.gsp</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.java</string>
			<key>end</key>
			<string>(%)&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.gsp</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>source.java</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.block.scriptlet.gsp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{</string>
					<key>name</key>
					<string>punctuation.section.scope.begin.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\}</string>
					<key>name</key>
					<string>punctuation.section.scope.end.java</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<key>tags</key>
		<dict>
			<key>begin</key>
			<string>(&lt;%@)\s*(?=(attribute|include|page|tag|taglib|variable)\s)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.gsp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.gsp</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.template.include.gsp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G(attribute)(?=\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.attribute.gsp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=%&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.gsp</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.gsp</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.gsp</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.gsp</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(name|required|fragment|rtexprvalue|type|description)(=)((")[^"]*("))</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G(include)(?=\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.include.gsp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=%&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.gsp</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.gsp</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.gsp</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.gsp</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(file)(=)((")[^"]*("))</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G(page)(?=\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.page.gsp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=%&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.gsp</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.gsp</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.gsp</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.gsp</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(language|extends|import|session|buffer|autoFlush|isThreadSafe|info|errorPage|isErrorPage|contentType|pageEncoding|isElIgnored)(=)((")[^"]*("))</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G(tag)(?=\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.tag.gsp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=%&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.gsp</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.gsp</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.gsp</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.gsp</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(display-name|body-content|dynamic-attributes|small-icon|large-icon|description|example|language|import|pageEncoding|isELIgnored)(=)((")[^"]*("))</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G(taglib)(?=\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.taglib.gsp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=%&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.gsp</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.gsp</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.gsp</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.gsp</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(uri|tagdir|prefix)(=)((")[^"]*("))</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G(variable)(?=\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.variable.gsp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=%&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.gsp</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.gsp</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.gsp</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.gsp</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(name-given|alias|variable-class|declare|scope|description)(=)((")[^"]*("))</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>xml_tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s*)(?=&lt;gsp:(declaration|expression|scriptlet)&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.leading.erb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)(\s*$\n)?</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.trailing.erb</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#actions</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>actions</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(&lt;/?)(gsp:attribute)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.attribute.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(name|trim)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(&lt;/?)(gsp:body)(&gt;)</string>
							<key>name</key>
							<string>meta.tag.template.body.gsp</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;/?)(gsp:element)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.element.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(name)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;)(gsp:doBody)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>/&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.dobody.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(var|varReader|scope)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;/?)(gsp:forward)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>/?&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.forward.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(page)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;)(gsp:param)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>/&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.param.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(name|value)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;)(gsp:getProperty)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>/&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.getproperty.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(name|property)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;/?)(gsp:include)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>/?&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.include.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(page|flush)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;)(gsp:invoke)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>/&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.invoke.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(fragment|var|varReader|scope)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;)(gsp:output)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>/&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.output.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(omit-xml-declaration|doctype-root-element|doctype-system|doctype-public)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;/?)(gsp:plugin)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.plugin.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(type|code|codebase|name|archive|align|height|hspace|jreversion|nspluginurl|iepluginurl)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>&gt;</string>
							<key>match</key>
							<string>(&lt;/?)(gsp:fallback)(&gt;)</string>
							<key>name</key>
							<string>meta.tag.template.fallback.gsp</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;/?)(gsp:root)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.root.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(xmlns|version|xmlns:taglibPrefix)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;)(gsp:setProperty)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>/&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.setproperty.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(name|property|value)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>&gt;</string>
							<key>match</key>
							<string>(&lt;/?)(gsp:text)(&gt;)</string>
							<key>name</key>
							<string>meta.tag.template.text.gsp</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;/?)(gsp:useBean)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.gsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>/?&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.gsp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.tag.template.usebean.gsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(id|scope|class|type|beanName)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<key>directive</key>
				<dict>
					<key>begin</key>
					<string>(&lt;)(gsp:directive\.(?=(attribute|include|page|tag|variable)\s))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.gsp</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.gsp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>/&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.gsp</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.template.$3.gsp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\G(attribute)(?=\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=/&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(name|required|fragment|rtexprvalue|type|description)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\G(include)(?=\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=/&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(file)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\G(page)(?=\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=/&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(language|extends|import|session|buffer|autoFlush|isThreadSafe|info|errorPage|isErrorPage|contentType|pageEncoding|isElIgnored)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\G(tag)(?=\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=/&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(display-name|body-content|dynamic-attributes|small-icon|large-icon|description|example|language|import|pageEncoding|isELIgnored)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\G(variable)(?=\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.gsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=/&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.gsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.gsp</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.double.gsp</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.gsp</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.gsp</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(name-given|alias|variable-class|declare|scope|description)(=)((")[^"]*("))</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<key>embedded</key>
				<dict>
					<key>begin</key>
					<string>(&lt;)(gsp:(declaration|expression|scriptlet))(&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.template.$3.gsp</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.gsp</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.gsp</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.gsp</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.java</string>
					<key>end</key>
					<string>((&lt;)/)(gsp:\3)(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.template.$4.gsp</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.gsp</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>source.java</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.gsp</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.gsp</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.gsp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.java</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.gsp</string>
	<key>uuid</key>
	<string>ACB58B55-9437-4AE6-AF42-854995CF51DF</string>
</dict>
</plist>