blank_issues_enabled: false
contact_links:
  - name: Questions and ideas
    url: https://github.com/code-groovy/code-groovy/discussions
    about: Ask questions or discuss ideas before opening an issue.
